### ISSUE TITLE
make ParseError public

### ISSUE THREAD

**Issue by ryanr1230** [nicolas-cherel/rumblebars#5]
it would be helpful for dealing with ParseError in other applications if it was public.
I think right now all of the parse module is private so I'm not sure what the best way to do this would be

**Comment by nicolas-cherel** [comment]
Ha yes, It's a bit confusing, but ParseError is re-exported (pub use) in crate root (rumblebars::ParseError) so you should be able to use it that way.

see http://nicolas-cherel.github.io/rumblebars/rumblebars/enum.ParseError.html

**Comment by nicolas-cherel** [comment]
Note that parsing errors reporting is a bit crude right now, and does not give much useful information.

**Comment by ryanr1230** [comment]
Oh ok, sorry should've seen that in the documentation...
